version: '3'
services:
  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ./database/:/var/lib/mysql/
    ports:
      - 3310:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  php:
    build: php
    depends_on:
      - database
    volumes:
      - ../:/var/www/

  web:
    build: nginx
    volumes:
      - ../:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
    - 82:80

